### ISSUE TITLE
TypeError: PrepareChunksThread._delete() missing 1 required positional argument: 'chunk_index'

### ISSUE THREAD

**Issue by lukasschmit** [Lightning-AI/litdata#273]
## 🐛 Bug

Hi all, I'm encountering this crash when training with lightning/litdata/ddp in the dataloader:

```
litdata==0.2.16
lightning==2.3.3
torch==2.3.1
```

running in ubunt 22.04 with cuda 12.4.1 on 8x H100 node using lighting trainer & lightning datamodule for DDP.

```
Exception ignored in thread started by: <bound method Thread._bootstrap of <PrepareChunksThread(Thread-47, started daemon 140464237778496)>>
05:31:10Traceback (most recent call last):
05:31:10 File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
05:31:10 self._bootstrap_inner()
05:31:10 File "/usr/lib/python3.11/threading.py", line 1049, in _bootstrap_inner
05:31:10 self._delete()
05:31:10TypeError: PrepareChunksThread._delete() missing 1 required positional argument: 'chunk_index'
```

This crash occurs during validation epochs but after running for a while. Seems to me like there's an incorrect call to this _delete() function, perhaps related to shard eviction/async edge cases?

Thanks for the help!

**Comment by tchaton** [comment]
Weird. Maybe it is coming from there: https://github.com/Lightning-AI/litdata/blob/main/src/litdata/streaming/reader.py#L121. Normally, it should occur as we check if the list isn't empty but we could make the argument optional just in case.

**Comment by bhimrazy** [comment]
I got the similar issue while making an optimizing test in my Mac but not elsewhere
```
litdata                     0.2.18
```
```
from litdata import StreamingDataset, optimize


def compress(index):
    return index, index**2


if __name__ == "__main__":
    # Add some data
    folders = ["folder_1", "folder_2"]
    compression = "zstd"
    for folder in folders:
        optimize(
            fn=compress,
            inputs=list(range(100)),
            output_dir=folder,
            chunk_bytes="64MB",
            num_workers=2,
            compression=compression,
        )

        dataset = StreamingDataset(folder)
        print(folder, dataset[1])
```

**log**
```
(venv) bhimrajyadav~$python test.py 
Create an account on https://lightning.ai/ to optimize your data faster using multiple nodes and large machines.
Storing the files under /Users/bhimrajyadav/Developer/LightningAI/litdata/folder_1
Setup started with fast_dev_run=False.
Setup finished in 0.004 seconds. Found 100 items to process.
Starting 2 workers with 100 items. The progress bar is only updated when a worker finishes.
Workers are ready ! Starting data processing...
                                                                                                                     Rank 0 inferred the following `['int', 'int']` data format.                                    | 0/100 [00:00<?, ?it/s]
Rank 1 inferred the following `['int', 'int']` data format.
Worker 1 is terminating.
Worker 0 is terminating.
Worker 0 is done.
                                                                                                                     Worker 1 is done.█████████████████████████████████████████████████████▌               | 78/100 [00:04<00:01, 18.42it/s]
Progress: 100%|█████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 23.50it/s]
Workers are finished.
Finished data processing!
folder_1 (1, 1)
Create an account on https://lightning.ai/ to optimize your data faster using multiple nodes and large machines.
Storing the files under /Users/bhimrajyadav/Developer/LightningAI/litdata/folder_2
Setup started with fast_dev_run=False.
Setup finished in 0.001 seconds. Found 100 items to process.
Starting 2 workers with 100 items. The progress bar is only updated when a worker finishes.
Workers are ready ! Starting data processing...
                                                                                                                     Rank 1 inferred the following `['int', 'int']` data format.                                    | 0/100 [00:00<?, ?it/s]
Rank 0 inferred the following `['int', 'int']` data format.
Worker 0 is terminating.
Worker 1 is terminating.
Worker 1 is done.
                                                                                                                     Worker 0 is done.█████████████████████████████████████████████████████████▊           | 84/100 [00:04<00:00, 20.54it/s]
Progress: 100%|█████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 24.29it/s]
Workers are finished.
Finished data processing!
Exception ignored in thread started by: <bound method Thread._bootstrap of <PrepareChunksThread(Thread-2, started daemon 6132822016)>>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1077, in _bootstrap_inner
    self._delete()
TypeError: PrepareChunksThread._delete() missing 1 required positional argument: 'chunk_index'
folder_2 (1, 1)
```

# Device
```
Hardware Overview:
Model Name: MacBook Pro
Model Identifier: Mac14,7
Chip: Apple M2
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 8 GB

ProductName:            macOS
ProductVersion:         14.5
BuildVersion:           23F79
```

**Comment by tchaton** [comment]
Hey @lukasschmit. It should be fixed. Can you use the latest version of litdata v0.2.19. `pip install -U litdata`
