### ISSUE TITLE
Using Litdata for object detection dataset preparation size mismatch error

### ISSUE THREAD

**Issue by mohanreddypmr** [Lightning-AI/litdata#297]
ning will be suppressed for the rest of this program. 

```python
(Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
Traceback (most recent call last):
  File "/home/mohan/Documents/learning/cv_yolov8/data_load.py", line 8, in <module>
    for sample in dataloader:
  File "/home/mohan/.local/lib/python3.10/site-packages/litdata/streaming/dataloader.py", line 623, in __iter__
    for batch in super().__iter__():
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 42, in fetch
    return self.collate_fn(data)
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 154, in collate
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 154, in <dictcomp>
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 222, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 213, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 6, 5] at entry 0 and [1, 1, 5] at entry 1
```

data preparation optimised code

```python
import numpy as np
import litdata as ld
import cv2
import glob

def random_images(path):
    #fake_images = Image.fromarray(np.random.randint(0, 256, (32, 32, 3), dtype=np.uint8))
    image = cv2.imread(path)
    image = cv2.resize(image,(640,640))
    lb_path = path.replace('/images/','/labels/')
    lb_path = lb_path.replace("."+lb_path.split('.')[-1],'.txt')
    labels = np.loadtxt(lb_path).reshape(1,-1,5)
    data = {"image": image, "class": labels}
    return data

if __name__ == "__main__":
    
    files = glob.glob('data_yolov8/train/images/*')

    ld.optimize(
        fn=random_images,                   # the function applied to each input
        inputs=files,           # the inputs to the function (here it's a list of numbers)
        output_dir="my_optimized_dataset/train",  # optimized data is stored here
        num_workers=1,                      # The number of workers on the same machine
        chunk_bytes="64MB"                  # size of each chunk
    )

    files = glob.glob('data_yolov8/valid/images/*')

    ld.optimize(
        fn=random_images,                   # the function applied to each input
        inputs=files,           # the inputs to the function (here it's a list of numbers)
        output_dir="my_optimized_dataset/valid",  # optimized data is stored here
        num_workers=1,                      # The number of workers on the same machine
        chunk_bytes="64MB"                  # size of each chunk
    )

    files = glob.glob('data_yolov8/test/images/*')

    ld.optimize(
        fn=random_images,                   # the function applied to each input
        inputs=files,           # the inputs to the function (here it's a list of numbers)
        output_dir="my_optimized_dataset/test",  # optimized data is stored here
        num_workers=1,                      # The number of workers on the same machine
        chunk_bytes="64MB"                  # size of each chunk
    )`

#while using streamdataloader , I got above error when we increase the batch_size 1 to 2

import litdata as ld

dataset = ld.StreamingDataset('my_optimized_dataset/train', shuffle=True)
dataloader = ld.StreamingDataLoader(dataset,batch_size=2)

count = 0

for sample in dataloader:
    img, cls = sample['image'], sample['class']
    count = count+1

print(count)`
```

**Comment by tchaton** [comment]
Hey @mohanreddypmr.

Do you think you could provide a reproducible script with synthetic tensors ? Just like torch.zeros(...) ?

**Comment by senarvi** [comment]
It seems like the shape of the label tensor is [1, N, 5], where N varies between samples, so multiple samples cannot be stacked into a batch tensor.

**Comment by tchaton** [comment]
Hey @senarvi, are you labels like this when they are being optimized ? Or is it a bug from litdata encoding & decoding ? Again, a reproducible script would help to fix this if it comes from litdata ;)

**Comment by senarvi** [comment]
> ```python
>   File "/home/mohan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 213, in collate_tensor_fn
>     return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [1, 6, 5] at entry 0 and [1, 1, 5] at entry 1
> ```

No, I don't have this problem. Based on what @mohanreddypmr wrote, it seems to me like his labels have variable shape, and that's why collate doesn't work. If that's correct, it's not really related to LitData. Every sample needs to have the same shape or a custom `collate_fn` needs to be provided to `StreamingDataLoader`.

**Comment by mohanreddypmr** [comment]
thanks @senarvi , got it , i will add custom collate_fn
