### ISSUE TITLE
Optimize function raises error in Lightning Studio

### ISSUE THREAD

**Issue by deependujha** [Lightning-AI/litdata#305]
## 🐛 Bug

Running optimize function in lightning studio (linux) raises error: 
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
```

### To Reproduce

1. Run the following code in `lightning studio` or `linux`. (Not sure about mac, but not expecting to fail)
2. Code:
```python
import os
import random
from litdata import optimize

def compress_1(index):
    return (index, index ** 2 + random.random())

def compress_2(index):
    return (index, index ** 3 + random.random())

optimize(
    fn=compress_1,
    inputs=list(range(1000)),
    num_workers=os.cpu_count(),
    output_dir="data/output_dir_1",
    chunk_bytes="64MB",
)

optimize(
    fn=compress_2,
    inputs=list(range(1000,2000)),
    num_workers=os.cpu_count(),
    output_dir="data/output_dir_2",
    chunk_bytes="64MB",
)
```

### Stack trace
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/teamspace/studios/this_studio/create_dataset.py", line 11, in <module>
    optimize(
  File "/teamspace/studios/this_studio/litdata/src/litdata/processing/functions.py", line 445, in optimize
    data_processor.run(
  File "/teamspace/studios/this_studio/litdata/src/litdata/processing/data_processor.py", line 1076, in run
    self._create_process_workers(data_recipe, workers_user_items)
  File "/teamspace/studios/this_studio/litdata/src/litdata/processing/data_processor.py", line 1193, in _create_process_workers
    worker.start()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

### Environment

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information: LitData version: 0.2.22

### Additional context

This problem is bcoz of : [Pr issue](https://github.com/Lightning-AI/litdata/pull/298/files#diff-1a5c020dabb4ec9ed88fde5c164ea43746aa753ed79e3a99d256496a48ceb2feR919)

```python
       start_method = start_method or ("fork" if in_notebook() else "spawn")

        msg = f"Setting multiprocessing start_method to {start_method}. "
        if in_notebook() and start_method == "fork":
            msg += "Tip: Libraries relying on lock can hang with `fork`. To use `spawn` in notebooks, "
            msg += "move your code to files and import it within the notebook."
        print(msg)

        multiprocessing.set_start_method(start_method, force=True)
```

![Screenshot from 2024-08-06 11-05-01](https://github.com/user-attachments/assets/cc547e0d-538f-448c-b170-ade28f9a611e)

- IMO, for linux systems, we should use `fork`.

**Comment by deependujha** [comment]
My temporary fix is to simply force it to use `fork`.

But, the better fix might be something like:
```python
from sys import platform

if not in_notebook() and (platform == "linux" or platform == "linux2"):
    start_method = 'fork'

**Comment by deependujha** [comment]
@tchaton optimize function is not usable at all right now in linux. Should I immediately proceed with this and fix?

or, suggest a better approach. Optimize is not usable at all right now in the new version.

**Comment by tchaton** [comment]
Yeah, go for it.

**Comment by deependujha** [comment]
Closing the PR.

If you encounter the same issue:

- move your optimize function inside `__main__`.
```python
import os
from litdata import optimize

def compress(index):
    return (index, index ** 2)

output_dir = "s3://my-dummy-bucket-litdata/fix_issue/"

if __name__ == "__main__":
    optimize(
        fn=compress,
        inputs=list(range(300,400)),
        num_workers=2,
        output_dir=output_dir,
        chunk_bytes="64MB",
        mode="append",
    )

```
