### ISSUE TITLE
Tests related to torchaudio fail

### ISSUE THREAD

**Issue by deependujha** [Lightning-AI/litdata#344]
## 🐛 Bug

All tests related to torchaudio fail.

### To Reproduce

1. Make sure you've `torchaudio` installed.
2. Run tests.
3. All tests related to torchaudio fail: `test_load_torch_audio` & `test_load_torch_audio_from_wav_file`

```bash
def _exit_on_error(self, error: str) -> None:
        for w in self.workers:
            # w.join(0)
            w.terminate()  # already error has occurred. So, no benefit of processing further.
>       raise RuntimeError(f"We found the following error {error}.")
E       RuntimeError: We found the following error Traceback (most recent call last):
E         File "/home/deependu/litdata/src/litdata/processing/data_processor.py", line 678, in _handle_data_chunk_recipe
E           item_data_or_generator = self.data_recipe.prepare_item(current_item)
E                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E         File "/home/deependu/litdata/src/litdata/processing/functions.py", line 174, in _prepare_item
E           return self._fn(item_metadata)
E                  ^^^^^^^^^^^^^^^^^^^^^^^
E         File "/home/deependu/litdata/tests/processing/test_data_processor.py", line 1151, in create_synthetic_audio_file
E           torchaudio.save(f, data, 16000, format="wav")
E         File "/home/deependu/miniconda3/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 312, in save
E           backend = dispatcher(uri, format, backend)
E                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E         File "/home/deependu/miniconda3/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 222, in dispatcher
E           raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
E       RuntimeError: Couldn't find appropriate backend to handle uri <_io.BufferedWriter name='/tmp/pytest-of-deependu/pytest-1/test_load_torch_audio_from_wav0/0.wav'> and format wav.
```

### Expected behavior

- Tests should pass.
- I guess, the reason of not getting test fail in CI is bcoz `torchaudio` is not installed and it has pytest fixture:
```python
@pytest.mark.skipif(condition=not _TORCH_AUDIO_AVAILABLE or not _ZSTD_AVAILABLE, reason="Requires: ['torchaudio']")
```

**Comment by deependujha** [comment]
My bad! 

Torchaudio backend was not installed (`ffmpeg <7`) 😅

https://pytorch.org/audio/stable/installation.html#optional-dependencies

All tests pass.
