### ISSUE TITLE
`use_checkpoint=True` creates invalid config.json file

### ISSUE THREAD

**Issue by cyrildiagne** [Lightning-AI/litdata#403]
## 🐛 Bug

Setting `use_checkpoint=True` when calling `litdata.optimise()` creates a `.checkpoint/config.json` that is truncated and cannot be loaded/resumed from:

config.json
```
{"num_workers": 4, "workers_user_items": [[
```

If the process fails and I try to resume it I get this error:

```
Traceback (most recent call last):
  File "/home/cyril/workspace/convert_to_litdata.py", line 103, in <module>
    main()
  File "/home/cyril/workspace/convert_to_litdata.py", line 90, in main
    ld.optimize()
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/site-packages/litdata/processing/functions.py", line 447, in optimize
    data_processor.run()
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/site-packages/litdata/processing/data_processor.py", line 1054, in run
    self._load_checkpoint_config(workers_user_items)
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/site-packages/litdata/processing/data_processor.py", line 1336, in _load_checkpoint_config
    cfg = json.load(f)
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read())
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/cyril/miniconda3/envs/litdata/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 44 (char 43)
```

### To Reproduce

Code to reproduce the behavior:

<details>
  <summary>Code sample</summary>

```python
import os
import litdata as ld
from pathlib import Path
import av
import numpy as np
from torchvision import transforms
import io

def process_video(video_path, size=512):
    try:
        with av.open(str(video_path)) as container:
            stream = container.streams.video[0]
            fps = stream.average_rate

            ctx = av.Codec('h264', 'r').create()
            ctx.extradata = stream.codec_context.extradata
            
            transform = transforms.Compose([
                transforms.ToTensor(),
                transforms.CenterCrop(min(stream.height, stream.width)),
                transforms.Resize((size, size))
            ])

            with io.BytesIO() as output:
                out_container = av.open(output, mode='w', format='mp4')
                out_stream = out_container.add_stream('h264', rate=fps)
                out_stream.width = size
                out_stream.height = size
                out_stream.pix_fmt = 'yuv420p'
                
                for packet in container.demux(stream):
                    for frame in ctx.decode(packet):
                        img_tensor = transform(frame.to_ndarray(format='rgb24'))
                        img_np = (img_tensor.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
                        out_frame = av.VideoFrame.from_ndarray(img_np, format='rgb24')
                        
                        for packet in out_stream.encode(out_frame):
                            out_container.mux(packet)
                
                for packet in out_stream.encode(None):
                    out_container.mux(packet)
                
                out_container.close()
                video_bytes = output.getvalue()
        
        return {
            "name": video_path.name,
            "video_bytes": video_bytes
        }
    except Exception as e:
        print(f"Error processing {video_path}: {str(e)}")
        return None

def main():
    input_folder = "./videos"
    video_files = [Path(input_folder) / f for f in os.listdir(input_folder) 
                if f.lower().endswith(('.mp4', '.avi', '.mov', '.mkv'))]

    ld.optimize(
        fn=process_video,
        inputs=video_files,
        output_dir="./output",
        num_workers=4,
        chunk_bytes="256MB",
        use_checkpoint=True,
    )

if __name__ == "__main__":
    main()
```

</details>

### Expected behavior

I would expect the file `.checkpoint/config.json` to be a valid json file when the process is running.

### Additional context

<details>
  <summary>Environment detail</summary>

- PyTorch Version (e.g., 1.0): `2.5.0`
- OS (e.g., Linux): `Ubuntu 22.04.4 LTS`
- How you installed PyTorch (`conda`, `pip`, source): `conda`
- Python version: `3.10.14`
- Any other relevant information: `litdata==0.2.29`

</details>

**Comment by tchaton** [comment]
Hey @cyrildiagne. Can you share more context ? How did the process fail ? It seems it didn't have time to finish storing the json file.

**Comment by cyrildiagne** [comment]
Hey @tchaton, thanks for the feedback.

Yes I thought the same, since the first crash happened almost immediately due to a wrong input folder.

But I fixed this initial issue, and the process is currently running on my machine, but the `config.json` file still looks the same with the truncation issue.

Next to the `config.json` file, I now have 4 `checkpoint-<n>.json` files that seem valid:

```json
{"chunks": [{"chunk_bytes": 255994729, "chunk_size": 771, "filename": "chunk-0-0.bin", "dim": null}, {"chunk_bytes": 255955792, "chunk_size": 765, "filename": "chunk-0-1.bin", "dim": null}, {"chunk_bytes": 255601811, "chunk_size": 767, "filename": "chunk-0-2.bin", "dim": null}, {"chunk_bytes": 255746049, "chunk_size": 775, "filename": "chunk-0-3.bin", "dim": null}, {"chunk_bytes": 255674577, "chunk_size": 775, "filename": "chunk-0-4.bin", "dim": null}, {"chunk_bytes": 255665768, "chunk_size": 774, "filename": "chunk-0-5.bin", "dim": null}, {"chunk_bytes": 255997697, "chunk_size": 782, "filename": "chunk-0-6.bin", "dim": null}, {"chunk_bytes": 255920400, "chunk_size": 779, "filename": "chunk-0-7.bin", "dim": null}, {"chunk_bytes": 255849102, "chunk_size": 772, "filename": "chunk-0-8.bin", "dim": null}, {"chunk_bytes": 255697315, "chunk_size": 782, "filename": "chunk-0-9.bin", "dim": null}, {"chunk_bytes": 255974914, "chunk_size": 776, "filename": "chunk-0-10.bin", "dim": null}, {"chunk_bytes": 255708646, "chunk_size": 779, "filename": "chunk-0-11.bin", "dim": null}, {"chunk_bytes": 255893872, "chunk_size": 784, "filename": "chunk-0-12.bin", "dim": null}, {"chunk_bytes": 255659141, "chunk_size": 776, "filename": "chunk-0-13.bin", "dim": null}, {"chunk_bytes": 255690865, "chunk_size": 775, "filename": "chunk-0-14.bin", "dim": null}, {"chunk_bytes": 255777659, "chunk_size": 786, "filename": "chunk-0-15.bin", "dim": null}, {"chunk_bytes": 255902641, "chunk_size": 778, "filename": "chunk-0-16.bin", "dim": null}, {"chunk_bytes": 255860648, "chunk_size": 776, "filename": "chunk-0-17.bin", "dim": null}, {"chunk_bytes": 255881961, "chunk_size": 780, "filename": "chunk-0-18.bin", "dim": null}, {"chunk_bytes": 255952712, "chunk_size": 774, "filename": "chunk-0-19.bin", "dim": null}, {"chunk_bytes": 255691942, "chunk_size": 777, "filename": "chunk-0-20.bin", "dim": null}, {"chunk_bytes": 255752475, "chunk_size": 774, "filename": "chunk-0-21.bin", "dim": null}, {"chunk_bytes": 255666110, "chunk_size": 771, "filename": "chunk-0-22.bin", "dim": null}, {"chunk_bytes": 255662462, "chunk_size": 774, "filename": "chunk-0-23.bin", "dim": null}, {"chunk_bytes": 255998184, "chunk_size": 764, "filename": "chunk-0-24.bin", "dim": null}, {"chunk_bytes": 255961041, "chunk_size": 778, "filename": "chunk-0-25.bin", "dim": null}, {"chunk_bytes": 255756205, "chunk_size": 770, "filename": "chunk-0-26.bin", "dim": null}], "config": {"compression": null, "chunk_size": null, "chunk_bytes": 256000000, "data_format": ["str", "bytes"], "data_spec": "[1, {\"type\": \"builtins.dict\", \"context\": \"[\\\"name\\\", \\\"video_bytes\\\"]\", \"children_spec\": [{\"type\": null, \"context\": null, \"children_spec\": []}, {\"type\": null, \"context\": null, \"children_spec\": []}]}]", "encryption": null, "item_loader": "PyTreeLoader"}, "done_till_index": 20934}
```
I'm running the process on a local machine, and since it's will be fairly long (many days), I expect that I may face power or network failures.
Is this file is necessary to resume? Is there a way to manually fix it?

**Comment by cyrildiagne** [comment]
Oops, I missed that line in the logs: `Object of type PosixPath is not JSON serializable`.
Looks like the problem was passing a list of Path instead of strings for the input files. 
Problem is solved, apologies!
