### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by robmarkcole** [Lightning-AI/litdata#61]
## 🐛 Bug
I've created a dataset following the approach on https://lightning.ai/lightning-ai/studios/convert-spatial-data-to-lightning-streaming

On using the dataset I get 

```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.10/dist-packages/lightning/data/streaming/dataset.py", line 274, in __next__
    data = self.__getitem__(
  File "/code/common/datasets/streaming.py", line 20, in __getitem__
    image_name, mask, image = super().__getitem__(index)
  File "/usr/local/lib/python3.10/dist-packages/lightning/data/streaming/dataset.py", line 244, in __getitem__
    return self.cache[index]
  File "/usr/local/lib/python3.10/dist-packages/lightning/data/streaming/cache.py", line 135, in __getitem__
    return self._reader.read(index)
  File "/usr/local/lib/python3.10/dist-packages/lightning/data/streaming/reader.py", line 252, in read
    item = self._item_loader.load_item_from_chunk(index.index, index.chunk_index, chunk_filepath, begin)
  File "/usr/local/lib/python3.10/dist-packages/lightning/data/streaming/item_loader.py", line 104, in load_item_from_chunk
    return self.deserialize(data)
  File "/usr/local/lib/python3.10/dist-packages/lightning/data/streaming/item_loader.py", line 112, in deserialize
    serializer = self._serializers[data_format]
KeyError: 'str'
```

### To Reproduce

1. Run '....'
1. Scroll down to '....'
1. See error

#### Code sample
Dataset creation script: 
```python
import os
from litdata import optimize
from glob import glob
from typing import Optional, Tuple

# 1. List the files and associate the images and their masks
root = "/Volumes/Toshiba4TB/EDA/cloud_detection"
input_dir = f"{root}/tuning_split"
output_root = f"{root}/tuning_split_optimized"

def get_info(img_filepath: str) -> Optional[Tuple]:
    mask_filepath = img_filepath.replace("S2L1C.tif", "labels/manual_hq.tif")
    if not os.path.exists(mask_filepath):
        return None
    splits = img_filepath.split("/")
    name = f"{splits[7]}_{splits[8]}"
    return name, img_filepath, mask_filepath

def compress(data):
    name, image_filepath, mask_filepath = data
    return name, image_filepath, mask_filepath

train_images = glob(f"{input_dir}/train/*/*/S2L1C.tif")
train_inputs = []
for img in train_images:
    info = get_info(img)
    if info is not None:
        train_inputs.append(info)

val_inputs = []
val_images = glob(f"{input_dir}/val/*/*/S2L1C.tif")
for img in val_images:
    info = get_info(img)
    if info is not None:
        val_inputs.append(info)

test_inputs = []
test_images = glob(f"{input_dir}/test/*/*/S2L1C.tif")
for img in test_images:
    info = get_info(img)
    if info is not None:
        test_inputs.append(info)

# 4. Run the optimization
if __name__ == "__main__":
    optimize(
        fn=compress,
        inputs=train_inputs,
        output_dir=f"{output_root}/train",
        chunk_bytes="128MB",
    )

    optimize(
        fn=compress,
        inputs=val_inputs,
        output_dir=f"{output_root}/val",
        chunk_bytes="128MB",
    )

    optimize(
        fn=compress,
        inputs=test_inputs,
        output_dir=f"{output_root}/test",
        chunk_bytes="128MB",
    )
```

And the dataset:
```python
class SegmentationStreamingDataset(StreamingDataset):
    """
    Segmentation dataset with streaming

    Args:
        input_dir (str): Local directory or S3 location of the dataset
        transforms (Optional[Callable]): A transform that takes in an image and returns a transformed version.
    """

    def __init__(self, *args, transforms=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.transforms = transforms

    def __getitem__(self, index) -> dict:
        image_name, mask, image = super().__getitem__(index)

        with MemoryFile(image) as memfile:
            with memfile.open() as dataset:
                image = torch.from_numpy(dataset.read()).float()

        with MemoryFile(mask) as memfile:
            with memfile.open() as dataset:
                mask = torch.from_numpy(dataset.read()).long()

        sample = {"image": image, "mask": mask, "image_name": image_name}
        if self.transforms is not None:
            sample = self.transforms(sample)
        return sample
```
### Expected behavior

No errors

### Environment

```
lightning==2.2.1
lightning-cloud==0.5.64
lightning-utilities==0.10.0
lit==15.0.7
litdata==0.2.1
```

**Comment by robmarkcole** [comment]
I noticed in my dataloader script I was importing from `lightning` updating to `from litdata import StreamingDataLoader` appears to have resolved this issue
